ema_alpha:
  type: uniform
  default: 0.9  # More stable embedding updates
  range: [0.8, 0.95]  

max_cos_dist:
  type: uniform
  default: 0.15  # Stricter appearance matching
  range: [0.05, 0.2]

max_iou_dist:
  type: uniform
  default: 0.75  # More precise motion-based matching
  range: [0.7, 0.85]

max_age:
  type: randint
  default: 75  # Allows for longer occlusions
  range: [50, 100]

n_init:
  type: randint
  default: 3  # More robust track initialization
  range: [2, 3]

mc_lambda:
  type: uniform
  default: 0.92  # Faster adaptation to drone appearance changes
  range: [0.90, 0.999]

nn_budget:
  type: choice
  default: 200  # More embeddings for re-identification
  options: [150, 200]
